### List all Observations
GET http://localhost:8080/fhir/Observation
Accept: application/fhir+json

###

### Get Observation by ID
GET http://localhost:8080/fhir/Observation/1
Accept: application/fhir+json
