### Create Organization
POST http://localhost:8080/fhir/Organization
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "Organization",
  "name": "Kinderarztpraxis Wien",
  "address": [
    {
      "type": "both",
      "line": [
        "Hauptstraße 12"
      ],
      "city": "Wien",
      "postalCode": "1010",
      "country": "AT"
    }
  ]
}