### Create a new RelatedPerson
POST http://localhost:8080/fhir/RelatedPerson
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "RelatedPerson",
  "patient": {
    "reference": "Patient/40"
  },
  "relationship": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
          "code": "PRN",
          "display": "Parent"
        }
      ],
      "text": "Elternteil"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Müller",
      "given": [
        "Anna"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "+43 123 456789",
      "use": "home"
    }
  ]
}