### POST RelatedPerson
### Creates a new RelatedPerson record linked to a Patient
POST http://localhost:8080/fhir/RelatedPerson
Content-Type: application/fhir+json
Accept: application/fhir+json

{
  "resourceType": "RelatedPerson",
  "id": "relatedperson-4",
  "patient": {
    "reference": "Patient/14"
  },
  "relationship": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/v3-RoleCode",
          "code": "PRN",
          "display": "Parent"
        }
      ],
      "text": "Elternteil"
    }
  ],
  "name": [
    {
      "use": "official",
      "family": "Gruber",
      "given": [
        "Martin"
      ]
    }
  ],
  "telecom": [
    {
      "system": "phone",
      "value": "+43 732 123456",
      "use": "home"
    }
  ]
}